export const goods = [
  {
    name: '数听会员 · 30天',
    isRecommend: false,
    price: 4.9,
    oldPrice: 6,
    memberType: '1',
    rank: 1,
    isOnline: true,
  },
  {
      name: '半年会员 · 180天',
      isRecommend: false,
      price: 9.8,
      oldPrice: 36,
      memberType: '2',
      rank: 2,
      isOnline: false,
  },
  {
    name: '数听会员 · 365天',
    isRecommend: true,
    price: 9.6,
    oldPrice: 36,
    memberType: '4',
    rank: 2,
    isOnline: true,
  },
  {
      name: '三年会员 · 3 * 365天',
      isRecommend: true,
      price: 18,
      oldPrice: 216,
      memberType: '6',
      rank: 3,
      isOnline: false,
  },
  {
      name: '终身会员 ',
      isRecommend: false,
      price: 17,
      oldPrice: 68,
      memberType: '3',
      rank: 3,
      isOnline: true,
  },
];