export const goods = [
  {
    name: '月度会员 · 30天',
    isRecommend: false,
    price: 5.9,
    oldPrice: 6,
    memberType: '1',
    rank: 1,
  },
  // {
  //     name: '半年会员 · 180天',
  //     isRecommend: false,
  //     price: 9.8,
  //     oldPrice: 36,
  //     memberType: '2',
  //     rank: 2,
  // },
  {
    name: '一年会员 · 12月',
    isRecommend: true,
    price: 18,
    oldPrice: 216,
    memberType: '4',
    rank: 2,
  },
  // {
  //     name: '三年会员 · 3 * 365天',
  //     isRecommend: true,
  //     price: 18,
  //     oldPrice: 216,
  //     memberType: '6',
  //     rank: 3,
  // },
  {
      name: '终身会员 ',
      isRecommend: false,
      price: 68,
      oldPrice: 360,
      memberType: '5',
      rank: 3,
  },
];